quote_style = "AutoPreferDouble"
column_width = 120
indent_type = "Spaces"
indent_width = 2
collapse_simple_statement = 'ConditionalOnly'
# call_parentheses = 'NoSingleTable'
[sort_requires]
enabled = false
